### ISSUE TITLE
Script to mod the game

### ISSUE THREAD

**Issue by thejoshwolfe** [MyEyes/RandomizerMod#1]
The readme mentions a modified game with modding hooks installed. This is theoretically possible to do without distributing any proprietary code from the original game by distributing a script that patches the game. Lunar IPS is a popular format for this kind of thing, but i hate that program and can definitely do much better.

We should make a program the mods the game, and i'm thinking probably a C# program, since anyone who can play hollow knight will already be able to run C# programs.

**Comment by MyEyes** [comment]
That's fair enough and all, my main concern is with having source control on the things we are altering as well as documentation for people that want to write mods.

**Comment by thejoshwolfe** [comment]
Here's my plan to solve this problem: https://gist.github.com/thejoshwolfe/db369bebf6518227c830fffee12ddbec

**Comment by seresharp** [comment]
Wyza has gone through the trouble of removing all code in the Modding namespace from the dll, commenting it, and adding instructions on how to merge it with the game assembly here: https://github.com/seanpr96/HollowKnight.Modding
There is still the problem of adding the hooks to the proper locations in the game code, but Firzen and I are thinking of creating a branch of dnspy that is able to apply diff patches to solve this problem.

**Comment by MyEyes** [comment]
Closed
