### ISSUE TITLE
Building from source fails to find PlayerData fields

### ISSUE THREAD

**Issue by thejoshwolfe** [MyEyes/RandomizerMod#5]
I'm running into a weird error i'm getting in initialization. The RandomizerMod.dll from the published zip works fine, but when i build from source, then `typeof(PlayerData).GetField(var.name, BindingFlags.Public | BindingFlags.NonPublic)` returns `null` in `AddEntry`. results in `entries.Count == 0` and nothing being randomized.

So this means that `PlayerData.gotCharm_1` doesn't exist, i guess. Either that or there's some weird reflection thing blocking me. Or maybe something's gone wrong with dll dependencies. The weird thing is that I can make this work by just swapping out my built .dll with the published .dll without touching the ModdingAPI.

Any help would be appreciated, although I might be unable to work on this project until the weekend.

**Comment by seresharp** [comment]
This is a problem I had already fixed on my end, but I guess I forgot to push it here. In any case, it's up to date on here now.
