### ISSUE TITLE
Source for .png files?

### ISSUE THREAD

**Issue by thejoshwolfe** [MyEyes/RandomizerMod#6]
These images are deployed in the .zip file, but this repo doesn't contain them:

* `easy.png`
* `hard.png`
* `logo.png`
* `off.png`

Is this for copyright reasons (maybe the font is copyrighted or something)? Or was this an oversight perhaps?

**Comment by MyEyes** [comment]
Sean made them, so  I will wait for him to get back about this.

**Comment by seresharp** [comment]
Added images
